### ISSUE TITLE
Confirm our cabinet's name

### ISSUE THREAD

**Issue by LKKCExcalibur** [LKKCExcalibur/StudentUnion#1]
We need to create a Chinese name and an English name. Previously, some of us suggested Excalibur as the English name, but no Chinese names have been proposed yet. If you have any ideas about the Chinese name and some other suggestions for the English name, please don't hesitate to share your views.

**Comment by ThFlash** [comment]
test

**Comment by LKKCExcalibur** [comment]
"No Chinese Name" - Approved during A17G15's meeting
